title: FH0
email: clbcjt@gmail.com
baseurl: ""
url: ""
github_username: fh0

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: UA-153141349-1
